<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE resume [
    <!ELEMENT resume (personal, introduction, education, professionexperience, technicalskills, others*)>
    <!ELEMENT personal (personalinfo+)>
    <!ELEMENT personalinfo (personalinfoName, personalinfoPhone, personalinfoEmail)>
    <!ELEMENT personalinfoName EMPTY>
    <!ATTLIST personalinfoName name CDATA #REQUIRED>
    <!ELEMENT personalinfoPhone EMPTY>
    <!ATTLIST personalinfoPhone phonenumber CDATA #REQUIRED>
    <!ELEMENT personalinfoEmail EMPTY>
    <!ATTLIST personalinfoEmail email CDATA #REQUIRED>
    <!ELEMENT introduction ANY >
    <!ELEMENT education (institute+)>
    <!ELEMENT institute (instituteName, instituteType, instituteYearStart, instituteYearEnd, instituteMajor)>
    <!ELEMENT instituteName (#PCDATA)>
    <!ELEMENT instituteType (#PCDATA)>
    <!ELEMENT instituteYearStart (#PCDATA)>
    <!ELEMENT instituteYearEnd (#PCDATA)>
    <!ELEMENT instituteMajor (#PCDATA)>
    <!ELEMENT professionexperience (pexp+)>
    <!ELEMENT pexp (pexpEmployer, pexpDesignation, pexpProject, pexpYearStart, pexpYearEnd?, pexpDescription)>
    <!ELEMENT pexpEmployer (#PCDATA)>
    <!ELEMENT pexpDesignation (#PCDATA)>
    <!ELEMENT pexpProject (#PCDATA)>
    <!ELEMENT pexpYearStart (#PCDATA)>
    <!ELEMENT pexpYearEnd (#PCDATA)>
    <!ELEMENT pexpDescription (#PCDATA)>
    <!ELEMENT technicalskills (skills)>
    <!ELEMENT skills (#PCDATA)>
    <!ATTLIST skills
        domain CDATA "Mobile"
        languagues CDATA "Computer Programming"
        skills CDATA "Computer Frameworks"
        procotols CDATA "TCP/IP"
        databases CDATA #IMPLIED
        OS CDATA #IMPLIED
    >
    <!ELEMENT others (#PCDATA)>
]>
<resume>
    <personal>
        <personalinfo>
            <personalinfoName name="Thanos of Titan" />
            <personalinfoPhone phonenumber="821034094034" />
            <personalinfoEmail email="bollamr2@illinois.edu" />
        </personalinfo>
    </personal>
    <introduction>I am a mobile communications specialist with over 15 years of experience in
        software development. I designed and developed messaging solutions client and
        server for mobile devices. Messaging technologies that worked on includes IP-Based
        Multimedia Subsystem (IMS), VoLTE and RCS Services on mobile networks.
        Currently I am involved with development of “Messaging as a Platform” (MAAP)
        Solution based on GMSA RCS and RCS Application Server. I have in-depth knowledge
        on IMS, xMS, VoLTE communication protocols in wireless network.
        I’m currently working as Senior Engineer at Samsung Electronics, Suwon, South
        Korea in Mobile Communication Business.</introduction>
    <education>
        <institute>
            <instituteName>University of Illinois Urbana-Champaign</instituteName>
            <instituteType>PostGraduation</instituteType>
            <instituteYearStart>2019</instituteYearStart>
            <instituteYearEnd>2021</instituteYearEnd>
            <instituteMajor>MCS-DS</instituteMajor>
        </institute>
        <institute>
            <instituteName>Birla Institute of Technology</instituteName>
            <instituteType>Graduation</instituteType>
            <instituteYearStart>2000</instituteYearStart>
            <instituteYearEnd>2004</instituteYearEnd>
            <instituteMajor>Bachelors in Computer Science</instituteMajor>
        </institute>
    </education>
    <professionexperience>
        <pexp>
            <pexpEmployer>Samsung Electornics, Suwon</pexpEmployer>
            <pexpDesignation>Software Engineer</pexpDesignation>
            <pexpProject>RCS Application Server</pexpProject>
            <pexpYearStart>2019</pexpYearStart>
            <pexpDescription>RCS Application Server to provide RCS and MAAP Services for
                Mobile Handsets.
                Design and Development of registration service and presence service.
                Provide ELK, Prometheus, and Grafana Interface for metrics and performance.</pexpDescription>
        </pexp>
        <pexp>
            <pexpEmployer>Samsung Electornics, Suwon</pexpEmployer>
            <pexpDesignation>Software Engineer</pexpDesignation>
            <pexpProject>RCS Application Server</pexpProject>
            <pexpYearStart>2017</pexpYearStart>
            <pexpYearEnd>2019</pexpYearEnd>
            <pexpDescription>Platform with a complete framework to build and deploy intelligent
                chat bots for providing RCS users a great conversational experience.
                Design and Development of micro services for Bot Life Cycle management,
                Bot Interface with MAAP, MAAP Core Services and RCS Client Service.
                Development of RCS client on Mobile Handset to connect to Chatbot.
                Development of MAAP RCS compliant micro service on MAAP platform.
                Development of smart bots to test and verify bot platform.
                Customization, Deployment and Maintenance of MAAP Solution on AWS
                Instance using various AWS Services for different mobile Operators.</pexpDescription>
        </pexp>
        <pexp>
            <pexpEmployer>Kyocera Wirless India</pexpEmployer>
            <pexpDesignation>Software Engineer</pexpDesignation>
            <pexpProject>CDMA Mobile Handsets Development</pexpProject>
            <pexpYearStart>2004</pexpYearStart>
            <pexpYearEnd>2007</pexpYearEnd>
            <pexpDescription>Development of mobile applications for US Operators.
                Development of FOTA Client Download Manager based on OMA Requirements
                in Kyocera Native Platform.
                Bug fixing in Multimedia Messaging Service 2.0 for USA operators.</pexpDescription>
        </pexp>
    </professionexperience>
    <technicalskills>
        <skills domain="Mobile Communications Solutions Development" languagues="Kotlin, Golang, C, C++, Java" skills="Kubernetes, Docker, Vertx, ELK, Grafana, Prometheus" procotols="RCS, SIP, MSRP, RTP/RTCP, TCP/IP, MMS, EMS, CMAS, SMS" databases="Mysql, redis" OS="Android, Linux" />
    </technicalskills>
    <others>PLEASE PLEASE PLEASE PLEASE HIRE ME.</others>
</resume> 